# Generated by Django 3.2.8 on 2021-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_greeting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type', models.CharField(max_length=200)),
                ('num_ships', models.IntegerField()),
            ],
        ),
    ]
